"""End-to-end tests: run analyze_file() against the synthetic fixtures in
seed_files/ (generated by scripts/generate_fixtures.py) and assert each
one is classified the way its construction demands.

These fixtures are hand-crafted byte structures standing in for real
captures (see the fixture generator's module docstring) — run against
real phone/WhatsApp/browser output before trusting this for a demo.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from traceq.analyze import analyze_file, analyze_file_with_descriptors
from traceq.matching import StoredFile
from traceq.models import Verdict

FIXTURES_DIR = Path(__file__).resolve().parent.parent / "seed_files"

pytestmark = pytest.mark.skipif(
    not FIXTURES_DIR.exists() or not any(FIXTURES_DIR.iterdir()),
    reason="run scripts/generate_fixtures.py first",
)


def _load(name: str) -> bytes:
    return (FIXTURES_DIR / name).read_bytes()


def _analyze(name: str, prior=None):
    return analyze_file(_load(name), name, prior or [])


def test_direct_phone_camera_is_verified_origin():
    r = _analyze("direct_phone_camera.jpg")
    assert r.verdict == Verdict.VERIFIED_ORIGIN
    assert "direct_phone_camera" in {m.name for m in r.record.pipeline_matches}
    assert r.record.exif.has_thumbnail_ifd is True
    assert r.record.exif.make == "TECNO"


def test_openai_generation_png_is_verified_origin_via_c2pa():
    r = _analyze("openai_generation.png")
    assert r.verdict == Verdict.VERIFIED_ORIGIN
    assert r.record.c2pa.present is True
    assert r.record.c2pa.software_agent == "gpt-image"
    assert "trainedAlgorithmicMedia" in (r.record.c2pa.digital_source_type or "")
    assert "openai_generation" in {m.name for m in r.record.pipeline_matches}


def test_openai_generation_jpeg_is_verified_origin_via_c2pa():
    r = _analyze("openai_generation.jpg")
    assert r.verdict == Verdict.VERIFIED_ORIGIN
    assert r.record.c2pa.present is True


def test_whatsapp_transmission_pipeline_detected():
    r = _analyze("whatsapp_transmission.jpg")
    names = {m.name for m in r.record.pipeline_matches}
    assert "whatsapp_transmission" in names
    assert r.record.encoder.is_progressive is True
    assert r.record.encoder.quant_tables_identical is True
    assert r.record.exif.present is False


def test_android_screenshot_pipeline_detected():
    r = _analyze("android_screenshot.png")
    names = {m.name for m in r.record.pipeline_matches}
    assert "android_screenshot" in names
    assert r.record.exif.software == "Android 13"


def test_android_camera_reshared_pipeline_detected():
    r = _analyze("android_camera_reshared.jpg")
    names = {m.name for m in r.record.pipeline_matches}
    assert "android_camera_reshared" in names
    assert r.record.icc.copyright == "Google Inc. 2016"
    assert r.record.exif.present is False


def test_near_lossless_export_pipeline_detected():
    r = _analyze("near_lossless_export.jpg")
    names = {m.name for m in r.record.pipeline_matches}
    assert "near_lossless_export" in names


def test_screen_capture_pipeline_detected():
    r = _analyze("screen_capture.png")
    names = {m.name for m in r.record.pipeline_matches}
    assert "screen_capture" in names
    assert r.record.min_flat_region_std == 0.0


def test_reportlab_pdf_pipeline_detected():
    r = _analyze("reportlab_programmatic.pdf")
    names = {m.name for m in r.record.pipeline_matches}
    assert "reportlab_programmatic_pdf" in names


def test_browser_print_pdf_pipeline_detected():
    r = _analyze("browser_print_to_pdf.pdf")
    names = {m.name for m in r.record.pipeline_matches}
    assert "browser_print_to_pdf" in names


def test_ilovepdf_pipeline_detected():
    r = _analyze("ilovepdf_compressed.pdf")
    names = {m.name for m in r.record.pipeline_matches}
    assert "ilovepdf_compression" in names


def test_no_record_when_nothing_verifiable():
    r = _analyze("no_record.jpg")
    assert r.verdict == Verdict.NO_RECORD
    assert r.record.c2pa.present is False
    assert r.record.exif.present is False


def test_derived_verdict_from_session_match_crop():
    parent, parent_descriptors = analyze_file_with_descriptors(_load("direct_phone_camera.jpg"), "direct_phone_camera.jpg")
    prior = [
        StoredFile(
            file_id=parent.file_id,
            filename=parent.filename,
            sha256=parent.record.sha256,
            phash=parent.record.phash,
            dhash=parent.record.dhash,
            ahash=parent.record.ahash,
            whash=parent.record.whash,
            width=parent.record.width,
            height=parent.record.height,
            pipeline_matches=parent.record.pipeline_matches,
            orb_descriptors=parent_descriptors,
        )
    ]
    cropped = _analyze("direct_phone_camera_cropped.jpg", prior)
    assert cropped.verdict == Verdict.DERIVED
    assert cropped.derivation is not None
    assert cropped.derivation.parent_sha256 == parent.record.sha256
    assert "cropped" in cropped.derivation.transformations_detected

    resized = _analyze("direct_phone_camera_resized.jpg", prior)
    assert resized.verdict == Verdict.DERIVED
    assert any("resized" in t for t in resized.derivation.transformations_detected)


def test_no_derived_match_without_prior_files():
    cropped = _analyze("direct_phone_camera_cropped.jpg")
    assert cropped.verdict != Verdict.DERIVED


def test_unrelated_files_are_never_falsely_derived():
    """Regression test: ahash/whash alone previously false-positived a
    DERIVED match between two unrelated synthetic images (distance 4,
    lower than the legitimate crop's own ahash/whash distance). Matching
    must never claim a relationship it can't back with phash/dhash or
    genuine ORB feature correspondence."""
    unrelated_pairs = [
        ("openai_generation.png", "no_record.jpg"),
        ("openai_generation.png", "android_camera_reshared.jpg"),
        ("no_record.jpg", "android_camera_reshared.jpg"),
        ("whatsapp_transmission.jpg", "near_lossless_export.jpg"),
    ]
    for parent_name, child_name in unrelated_pairs:
        parent, parent_descriptors = analyze_file_with_descriptors(_load(parent_name), parent_name)
        prior = [
            StoredFile(
                file_id=parent.file_id,
                filename=parent.filename,
                sha256=parent.record.sha256,
                phash=parent.record.phash,
                dhash=parent.record.dhash,
                ahash=parent.record.ahash,
                whash=parent.record.whash,
                width=parent.record.width,
                height=parent.record.height,
                pipeline_matches=parent.record.pipeline_matches,
                orb_descriptors=parent_descriptors,
            )
        ]
        child = _analyze(child_name, prior)
        assert child.verdict != Verdict.DERIVED, f"{child_name} was falsely linked to {parent_name}"


def test_format_mismatch_detected_when_extension_lies():
    data = _load("direct_phone_camera.jpg")
    r = analyze_file(data, "not_actually.png")
    assert r.record.actual_format == "jpeg"
    assert r.record.declared_format == "png"
    assert r.record.format_mismatch is True


def test_trace_score_never_exceeds_max_and_c2pa_dominates():
    r = _analyze("openai_generation.png")
    assert r.trace_score.value <= r.trace_score.max_value
    assert r.trace_score.breakdown.get("valid_c2pa_manifest_present") == 40


def test_stats_never_leak_into_verdict_or_score_fields():
    """ForensicStats must remain diagnostics-only: it should never appear
    inside the trace_score breakdown or verdict statement."""
    for name in ["direct_phone_camera.jpg", "whatsapp_transmission.jpg", "no_record.jpg"]:
        r = _analyze(name)
        assert "noise" not in r.verdict_statement.lower()
        assert "chromatic" not in r.verdict_statement.lower()
        for key in r.trace_score.breakdown:
            assert "noise" not in key and "chromatic" not in key


def test_no_record_statement_matches_exact_contract_text():
    r = _analyze("no_record.jpg")
    assert r.verdict_statement == (
        "No chain of custody found for this file. Content credentials are "
        "commonly removed by screenshots, messaging apps, and re-encoding."
    )
